/**
 * A worked example of a completed call, shown before anyone presses Start.
 *
 * The section used to open on an empty transcript, which meant a viewer had to place a
 * call before there was anything to look at — and in front of a room that is the worst
 * possible first impression. This is the same call the demo script walks through, already
 * played out, so the page explains itself at a glance: the detection panel, the stage
 * tracker and the captured profile are all populated the moment the section opens.
 *
 * It is labelled on screen as a recorded example and it is NOT live: no Bhashini request
 * is made for it, nothing is written to Firestore, and it never reaches Completed Calls
 * or the Gap Map. Pressing Start replaces it with a real call.
 *
 * ── Why it reads the way it does ──
 *
 * The call opens with the bilingual greeting — Hindi, then English — and then runs
 * entirely in Hindi, because that is exactly what a real call does. `useVoiceCall` speaks
 * `greetingHi.hi` followed by `greetingEn.en`, detects the caller's language from their
 * first reply, and from then on takes every line from the detected language
 * (`language = detection.languageCode === 'en' ? 'en' : 'hi'`). This caller is detected as
 * Hindi, so every SETU turn after the greeting is the Hindi line — the same string the
 * live call would use, read from lines.json rather than retyped here.
 *
 * The caller's replies are in Devanagari because that is what Bhashini's Hindi ASR
 * returns. Showing them romanised would misrepresent what the transcript actually holds.
 *
 * The recommendation, enrolment and closing lines are generated by the same functions the
 * live call uses, so the course, the distance, the duration and the fee wording cannot
 * drift away from the course record.
 */

import { courseRecord, type MatchResult } from '../data/courseCatalogue'
import type { LanguageDetection } from '../lib/languageDetection'
import { enrolmentLine, LINES, recommendationLine, type CallState, type Profile, type Turn } from './script'

/** The assistant's own line, in the language the call is being held in. */
function setu(id: string, stage: Turn['stage'], language: 'hi' | 'en' = 'hi'): Turn {
  return { speaker: 'setu', text: LINES[id]?.[language] ?? '', stage }
}

function caller(text: string, stage: Turn['stage']): Turn {
  return { speaker: 'caller', text, stage }
}

/**
 * Sunita Devi of Tetartoli, Ghaghra block, Gumla — the caller from the demo script.
 * Five years of schooling, sews at home already, cannot travel far, no smartphone.
 * Tailoring L1 at the Ghaghra centre is 3 km away, has seats, and needs no reading.
 */
const PROFILE: Profile = {
  name: 'सुनीता देवी',
  village: 'टेटरटोली',
  block: 'Ghaghra',
  district: 'Gumla',
  currentWork: 'खेत में मज़दूरी',
  familyOccupation: 'घर पर सिलाई',
  familyTrade: 'Tailoring',
  schoolYears: 5,
  literacy: 'low',
  interests: ['tailoring'],
  mobility: 'cannot-travel',
  hasSmartphone: false,
  workPreference: 'self-employment',
  secondaryNumber: '+91 93348 10410',
  isBasicPhoneOnly: true,
  consent: true,
  anonymous: false,
}

const MATCH: MatchResult | null = (() => {
  const course = courseRecord('Tailoring L1')
  if (!course) return null
  return {
    course,
    centreName: 'Ghaghra Training Centre',
    centreBlock: 'Ghaghra',
    centreDistrict: 'Gumla',
    distanceKm: 3,
    seatsLeft: 6,
    reasons: ['interest', 'family-trade', 'close', 'own-work', 'local-demand'],
    localDemand: true,
  }
})()

/** Stage 14's closing line, worded exactly as useVoiceCall words it in Hindi. */
const CLOSING = `मैं यह आपके फ़ोन पर संदेश के रूप में भेज रही हूँ। कुछ दिनों में कोई आपको फ़ोन करके पूछेगा कि आप जुड़ पाए या नहीं। धन्यवाद, ${PROFILE.name}।`

function buildTurns(): Turn[] {
  const turns: Turn[] = [
    // Stage 1: the greeting is the one bilingual moment — Hindi, then English — because
    // at this point nobody knows yet which language the caller speaks.
    setu('greetingHi', 'greeting', 'hi'),
    setu('greetingEn', 'greeting', 'en'),
    caller('हाँ… नमस्ते। मैं सुन रही हूँ।', 'greeting'),

    // Both models answered Hindi, so the rest of the call is held in Hindi.
    setu('consent', 'consent'),
    caller('हाँ, ठीक है।', 'consent'),

    setu('name', 'name'),
    caller('सुनीता देवी।', 'name'),

    setu('location', 'location'),
    caller('टेटरटोली गाँव, घाघरा प्रखंड।', 'location'),

    setu('work', 'work'),
    caller('खेत में मज़दूरी करती हूँ, जब काम मिलता है।', 'work'),

    setu('family', 'family'),
    caller('माँ सिलाई करती थीं, घर पर ही।', 'family'),

    setu('education', 'education'),
    caller('पाँचवीं तक पढ़ी हूँ। ज़्यादा पढ़ना नहीं आता।', 'education'),
    // Script rule 5: never sound surprised at a low answer.
    setu('educationNone', 'education'),

    setu('interest', 'interest'),
    caller('सिलाई सीखना चाहती हूँ। थोड़ा आता है, पर सही से नहीं।', 'interest'),

    setu('travel', 'travel'),
    caller('दूर नहीं जा सकती। घर में बच्चे हैं।', 'travel'),

    // cannot-travel routes through connectivity before preference.
    setu('connectivity', 'connectivity'),
    caller('स्मार्टफ़ोन नहीं है। बेटे के पास है।', 'connectivity'),

    setu('preference', 'preference'),
    caller('घर पर ही कुछ काम कर लूँ तो ठीक रहेगा।', 'preference'),

    setu('secondary', 'secondary'),
    caller('बेटे का नंबर है — 93348 10410। उसमें व्हाट्सऐप भी है।', 'secondary'),
  ]

  if (MATCH) {
    // Generated by the live call's own functions, so the figures match the course record.
    turns.push(
      { speaker: 'setu', text: recommendationLine(MATCH, PROFILE, 'hi'), stage: 'recommendation' },
      caller('हाँ, बताइए।', 'recommendation'),
      { speaker: 'setu', text: enrolmentLine(MATCH, 'hi'), stage: 'enrolment' },
      caller('ठीक है। धन्यवाद।', 'enrolment'),
    )
  }

  // The live call files the closing line under 'done'; here it stays at 'close' so the
  // stage tracker reads as finished rather than blank.
  turns.push({ speaker: 'setu', text: CLOSING, stage: 'close' })
  return turns
}

/**
 * Both models agreed on Hindi, so this caller is one the stack serves well.
 * The contested case — where they disagree and the call is handed to a human — is the
 * other example, and it is rehearsed live with ?rehearse=contested.
 */
export const SAMPLE_DETECTION: LanguageDetection = {
  languageCode: 'hi',
  languageName: 'Hindi',
  confidence: 0.94,
  agreement: 'agreed',
  primary: {
    serviceId: 'bhashini/iitmandi/audio-lang-detection/gpu',
    langCode: 'hi',
    scriptCode: 'deva',
    langScore: 0.94,
  },
  secondary: {
    serviceId: 'bhashini/ald',
    langCode: 'hi',
    scriptCode: 'deva',
    langScore: 0.91,
  },
  provider: 'simulated',
}

/** The example as the experience renders it: a finished call sitting at the close stage. */
export function sampleCallState(): CallState {
  return {
    stage: 'close',
    profile: PROFILE,
    turns: buildTurns(),
    recommendation: MATCH,
    rejected: [],
    escalation: null,
    outcome: 'completed',
    unclear: 0,
    noLocalDemand: false,
    dialectGap: false,
  }
}
